function closing()

GO_p=uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.85 0.01 0.15 0.1],...
    'backgroundcolor','[0.8 0.6 0.9]',...
    'foregroundcolor','g',...
    'String','CLOSE',...
    'Callback','close');