Fig=figure('Name','The output and input voltage',...
    'Units','normalized',...
    'Position',[.1 .1 .7 .7],...
    'NumberTitle','off','color',[0.8 0.6 0.9] );

h = uimenu('Label','Menu');

uimenu(h,'Label','only VI','Callback','graphVI',...
    'Accelerator','m');

uimenu(h,'Label','only Vo','Callback','graphVo',...
    'Accelerator','L');

uimenu(h,'Label','Close','Callback','close',...
    'Separator','on','Accelerator','Q');

uimenu(h,'Label','Circuit picture','Callback','SimpleComparator',...
    'Separator','on','Accelerator','p');
VPS=1;
A=1;


grafic(VPS,A);

GO_e=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.9 0.7 0.16 0.05],...
    'foregroundcolor','b',...
    'String','VPS',...
    'Callback',['VPS=','str2num(get(gco,''String''));grafic(VPS,A);']);

GO_f=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.9 0.65 0.16 0.05],...
    'foregroundcolor','b',...
    'String','A',...
    'Callback','A=str2num(get(gco,''string''));grafic(VPS,A);');
