Fig=figure('Name','The input voltage',...
    'Units','normalized',...
    'Position',[.1 .1 .7 .7],...
    'NumberTitle','off','color',[0.8 0.6 0.9] );


closing();
graficVI(A)



GO_e=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.9 0.65 0.16 0.05],...
    'foregroundcolor','b',...
    'String','A',...
    'Callback','A=str2num(get(gco,''string''));graficVI(A);');
