function HysComparator
 Fig=figure('Name','The output and input voltage',...
     'Units','normalized',...
     'Position',[.1 .1 .7 .7],...
     'NumberTitle','off','color',[0.8 0.6 0.9] );
closing();

imshow('hysim.jpg');
i=gca;

set(i, 'Position', [0.05 0.2 0.6 0.7])
axis off;
title('Hysterisis comparator(non-inverting)');

GO_t=uicontrol('Style','text',...
    'Units','normalized',...
    'FontSize',16,...
    'Position',[0.65 0.7 0.3 0.1],...
    'backgroundcolor','[0.63 0.51 1]',...
    'foregroundcolor','black',...
    'String','Write values for R1 and R2:');

Go_x=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.72 0.6 0.16 0.05],...
    'foregroundcolor','black',...
     'backgroundcolor','[0.63 0.51 1]',...
    'String','R1');
  

Go_y= uicontrol('Style','edit',...
     'Units','normalized',...
    'Position',[0.72 0.55 0.16 0.05],...
    'foregroundcolor','black',...
     'backgroundcolor','[0.63 0.51 1]',...
    'String','R2');

Go_z=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.72 0.5 0.16 0.05],...
    'foregroundcolor','black',...
     'backgroundcolor','[0.63 0.51 1]',...
    'String','Vps');

 h = text(1.1, 0.2, 'The value of |Vth| is:', 'Units', 'normalized',...
     'FontSize',16);


GO_cal=uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.7 0.4 0.16 0.05],...
    'backgroundcolor','[0.8 0.6 0.9]',...
    'foregroundcolor','g',...
    'String','Calculate |Vth|',...
    'Callback',{@calculate_callback_Vth, Go_x, Go_y, Go_z,h});




