Fig=figure('Name','The output and input voltage',...
    'Units','normalized',...
    'Position',[.1 .1 .7 .7],...
    'NumberTitle','off','color',[0.8 0.6 0.9] );


graphHisInv(1);

GO_t=uicontrol('Style','text',...
    'Units','normalized',...
    'FontSize',18,...
    'Position',[0.001 0.6 0.05 0.1],...
    'backgroundcolor','[0.8 0.6 0.9]',...
    'foregroundcolor','black',...
    'String','Vth=');


popup = uicontrol('Style', 'popup',...
    'String', {'1','2','3','4','5'},...
    'Position', [20 340 100 50],...
    'Callback', @setVthInv);    


% GO_p=uicontrol('Style','pushbutton',...
%     'Units','normalized',...
%     'Position',[0.85 0.01 0.15 0.1],...
%     'backgroundcolor','[0.8 0.6 0.9]',...
%     'foregroundcolor','g',...
%     'String','CLOSE',...
%     'Callback','close');

closing();

h = uimenu('Label','Menu');

uimenu(h,'Label','Circuit picture','Callback','HysComparator_Inv',...
    'Separator','on','Accelerator','p');

uimenu(h,'Label','Non-inverting graph(back)','Callback','hysVIVo',...
    'Separator','on','Accelerator','l');

