close all;

Fig=figure('Name','Proiect',...
    'Units','normalized',...
    'Position',[.1 .1 .7 .7],...
    'NumberTitle','off','color',[0.8 0.6 0.9] );



GO_t=uicontrol('Style','text',...
    'Units','normalized',...
    'FontSize',18,...
    'Position',[0.37 0.7 0.3 0.1],...
    'backgroundcolor','[0.63 0.51 1]',...
    'foregroundcolor','black',...
    'String','Circuits with Operational Amplifiers');

imshow(grp3)

GO_t2=uicontrol('Style','text',...
    'Units','normalized',...
    'FontSize',14,...
    'Position',[0.7 0.1 0.13 0.1],...
    'backgroundcolor','[0.8 0.6 0.9]',...
    'foregroundcolor','black',...
    'String','By Zaicanu Raluca');

GO_f=uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.07 0.4 0.15 0.1],...
    'backgroundcolor','[0.9, 0.41, 0.9]',...
    'String','Problems',...
    'Callback','P1');

GO_e=uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.07 0.3 0.15 0.1],...
    'backgroundcolor','[0.9, 0.41, 0.9]',...
    'String','Documentation',...
    'Callback','doc');



GO_p=uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.85 0.01 0.15 0.1],...
    'backgroundcolor','[0.8 0.6 0.9]',...
    'foregroundcolor','g',...
    'String','CLOSE',...
    'Callback','close');



GO_rb1=uicontrol('Style','radiobutton',...
    'Units','normalized',...
    'Position',[0.4 0.5 .1 .1],...
    'backgroundcolor','[0.68 0.85 0.90]',...
    'String',' Simple Comparator',...
    'Callback','graphVIVo') ;


    
GO_rb2=uicontrol('Style','radiobutton',...
    'Units','normalized',...
    'Position',[0.4 0.4 .1 .1],...
    'backgroundcolor','[0.5 0.6 0.9]',...
    'String',' Hysteresis comparators',...
    'Callback','hysVIVo') ;

GO_rb3=uicontrol('Style','radiobutton',...
    'Units','normalized',...
    'Position',[0.4 0.3 .1 .1],...
    'backgroundcolor','[0.25 0.41 0.88]',...
    'String',' Amplifiers',...
    'Callback','AmplificatorVIVo') ;

